### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by nakhodnov17** [samik-saha/glyrics#18]
**System**
Windows 10.1803.17134, Chrome 74.0.3729.108
An error occurred while searching lyrics (generally speaking on any site). I think it related with wikia.com domain transfer to fandom.com. Since all requests to lyrics.wikia.com are redirected to lyrics.fandom.com and lyrics.fandom.com does not presented in "permissions" section in manifest any query will cause CORS violation error.
**Possible solution**
I suppose the possible solution is to add "\*://lyrics.fandom.com/\*" to "permissions" in manifest.
![image](https://user-images.githubusercontent.com/32146790/56855843-5e7f8f00-6957-11e9-8d6a-bae9cb01646b.png)
![image](https://user-images.githubusercontent.com/32146790/56855822-e4e7a100-6956-11e9-8049-9254e3197a97.png)

**Comment by samik-saha** [comment]
Thanks @nakhodnov17 . I have added updated the manifest as per your suggestion.

**Comment by nakhodnov17** [comment]
Thanks, now it's working fine.
