### ISSUE TITLE
Doesn't work on Spotify

### ISSUE THREAD

**Issue by atos93** [samik-saha/glyrics#8]
The app replicate the title with Spotify and not find the song on LyricWiki 
Example:
![image](https://user-images.githubusercontent.com/15677399/48978665-31c90200-f0af-11e8-9441-770aeb599d37.png)

**Comment by samik-saha** [comment]
@atos93 could you check now if the issue is resolved?

**Comment by atos93** [comment]
Yes now it works. Thanks
